 # ========================================================
    # IRC CENSUS REPORT
    # ========================================================
    "irc_census_report": {
        # ----------------------------------------------------
        # Modules
        # ----------------------------------------------------
        "module_name": "irc_census_report",
        "repo_module": "irc_census_report_repo",
        "service_module": "irc_census_report_service",
        "handler_module": "irc_census_report",

        # ----------------------------------------------------
        # Repository
        #
        # Generated by generate_repo_stack.py from
        # irc_census_report_config.json:
        #
        # get_irc_census_reports(
        #     filters=None,
        #     sort=None,
        #     page=None,
        #     columns=None,
        # )
        #
        # get_irc_census_report_by_id(
        #     row_id,
        #     filters=None,
        #     page=None,
        #     columns=None,
        #     sort=None,
        # )
        # ----------------------------------------------------
        "repo_search_function": "get_irc_census_reports",
        "repo_key_function": "get_irc_census_report_by_id",

        # ----------------------------------------------------
        # Service
        #
        # search_irc_census_reports(
        #     filters=None,
        #     sort=None,
        #     page=None,
        #     columns=None,
        # )
        #
        # get_irc_census_report_details(
        #     row_id,
        #     filters=None,
        #     limit=settings.DEFAULT_PAGE_SIZE,
        #     cursor=None,
        #     columns=None,
        #     sort=None,
        # )
        # ----------------------------------------------------
        "service_search_function": "search_irc_census_reports",
        "service_key_function": "get_irc_census_report_details",

        # ----------------------------------------------------
        # Handler
        #
        # GET  /v1/irc-census-reports/{row_id}
        #     get_irc_census_report_v1
        #
        # POST /v1/irc-census-reports/search
        #     search_irc_census_reports_v1
        #
        # GET  /v1/irc-census-reports
        #     list_irc_census_reports_v1
        # ----------------------------------------------------
        "handler_search_function": "search_irc_census_reports_v1",
        "handler_list_function": "list_irc_census_reports_v1",
        "handler_key_function": "get_irc_census_report_v1",

        # ----------------------------------------------------
        # Domain models
        # ----------------------------------------------------
        "response_model": "IrcCensusReportResponse",
        "search_response_model": (
            "IrcCensusReportSearchServiceResponse"
        ),

        # ----------------------------------------------------
        # Key
        #
        # Repository QuerySpec:
        # logical_id_field = "row_id"
        # ----------------------------------------------------
        "key_column": "row_id",
        "key_argument": "row_id",
        "handler_path_parameter": "row_id",
        "sample_key": "1001",

        # Search endpoint itself does NOT require row_id.
        # Detail endpoint DOES require row_id.
        "search_requires_key": False,
        "key_lookup_requires_key": True,

        # ----------------------------------------------------
        # Supported operations
        # ----------------------------------------------------
        "supports_search": True,
        "supports_list": True,
        "supports_key_lookup": True,
        "supports_handler_key_lookup": True,

        # ----------------------------------------------------
        # Repository function signatures
        # ----------------------------------------------------
        "repo_search_parameters": [
            "filters",
            "sort",
            "page",
            "columns",
        ],

        "repo_key_parameters": [
            "row_id",
            "filters",
            "page",
            "columns",
            "sort",
        ],

        # ----------------------------------------------------
        # Service function signatures
        # ----------------------------------------------------
        "service_search_parameters": [
            "filters",
            "sort",
            "page",
            "columns",
        ],

        "service_key_parameters": [
            "row_id",
            "filters",
            "limit",
            "cursor",
            "columns",
            "sort",
        ],

        # ----------------------------------------------------
        # Handler -> service signatures
        # ----------------------------------------------------
        "handler_service_parameters": [
            "filters",
            "sort",
            "page",
            "columns",
        ],

        "handler_key_service_parameters": [
            "row_id",
            "filters",
            "limit",
            "cursor",
            "columns",
        ],

        "handler_list_service_parameters": [
            "filters",
            "page",
        ],

        # ----------------------------------------------------
        # Pagination / DB execution
        #
        # Repository calls:
        # execute_query(plan.sql, plan.params, limit=current_page.limit)
        # ----------------------------------------------------
        "repo_execute_query_passes_limit": True,
        "repo_pagination_mode": "page",
        "service_search_pagination_mode": "page",
        "service_key_pagination_mode": "limit_cursor",

        "default_sort_field": "row_id",
        "default_sort_order": "asc",

        # ----------------------------------------------------
        # Sample model data
        # ----------------------------------------------------
        "sample_field": "last_first_name",
        "sample_value": "Doe, Jane",

        "response_key_field": "row_id",
        "response_assert_fields": ["row_id"],

        # ----------------------------------------------------
        # V1 handler schemas
        # ----------------------------------------------------
        "handler_inner_schema": (
            "V1IrcCensusReportResponseModel"
        ),
        "handler_outer_schema": (
            "V1IrcCensusReportListResponseModel"
        ),
        "handler_detail_outer_schema": (
            "V1IrcCensusReportDetailResponseModel"
        ),

        # ----------------------------------------------------
        # Handler expectations
        # ----------------------------------------------------
        "handler_success_status": 200,
        "handler_missing_key_status": 400,
        "handler_not_found_status": 404,
        "handler_missing_key_message": (
            "IrcCensusReport ID is required."
        ),

        "handler_detail_route": (
            "/v1/irc-census-reports/{row_id}"
        ),
        "handler_search_route": (
            "/v1/irc-census-reports/search"
        ),
        "handler_list_route": (
            "/v1/irc-census-reports"
        ),

        "handler_filter_context": "IRC_CENSUS_REPORT_FILTER_CONTEXT",

        "generate_repo_tests": True,
        "generate_model_tests": True,
        "generate_service_tests": True,
        "generate_handler_tests": True,
    },
